### ISSUE TITLE
s2s lookup error

### ISSUE THREAD

**Issue by waveletlet** [ortuman/jackal#77]
jackal can't find a server, even though `dig` shows it resolves correctly.

```
2019-03-11 23:51:42 💥 [ERR] s2s/server:94 - lookup _xmpp-server._tcp.riotcat.org on 9.9.9.9:53: no such host
```

```
# dig riotcat.org

; <<>> DiG 9.10.3-P4-Debian <<>> riotcat.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59702
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;riotcat.org.			IN	A

;; ANSWER SECTION:
riotcat.org.		3586	IN	A	87.106.127.220

;; Query time: 0 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Mon Mar 11 23:52:57 UTC 2019
;; MSG SIZE  rcvd: 56
```

The error is consistent, I can't get any kind of connection to that server at all.

This isn't a global issue, I can successfully connect to other servers and send messages to users on them. According to [compliance.conversations.im](https://compliance.conversations.im/server/riotcat.org/), the remote server is running Prosody 0.11. 

Then when I was checking logs for more errors, I found that a server I can successfully communicate on is also returning the same error occasionally (`2019-03-12 01:54:52 💥 [ERR] s2s/server:94 - lookup _xmpp-server._tcp.chat.404.city on 9.9.9.9:53: no such host`). The remote server with the intermittent error is running  ejabberd 18.12.1-2~bpo9+1.

Maybe it's something I can tweak in the config? s2s section of jackal.yml is the same as in the example:

```
s2s:
    dial_timeout: 15
    dialback_secret: s3cr3tf0rd14lb4ck
    max_stanza_size: 131072

    transport:
      bind_addr: 0.0.0.0
      port: 5269
      keep_alive: 600
```
